---
abstract: 'Perl object oriented interface implementation to xxHash 64 bit algorithm'
author:
  - 'Bela Bodecs <bodecsb@vivanet.hu>'
build_requires:
  ExtUtils::CBuilder: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.19'
dynamic_config: 1
generated_by: 'Module::Build version 0.4229, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Digest-xxHash64
provides:
  Digest::xxHash64:
    file: lib/Digest/xxHash64.pm
    version: '1.01'
requires:
  Math::Int64: '0.54'
  XSLoader: '0'
resources:
  bugtracker: https://github.com/DoubleBB/digest-xxhash64/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/DoubleBB/digest-xxhash64
version: '1.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
